parameters:
  - name: switch
    type: boolean
    default: true
variables:
  - name: rootvar
    value: ${{ parameters.switch }}
stages:
  - ${{ if variables.rootvar }}:
    - stage:
      variables:
        - name: stagevar
          value: ${{ variables.rootvar }}
      jobs:
        - ${{ if variables.stagevar }}:
          - job:
            variables:
              - name: jobvar
                value: ${{ variables.stagevar }}
            steps:
              - ${{ if variables.jobvar }}:
                - script: echo '${{ converttojson(variables) }}'
              - ${{ else }}:
                - error: assert
        - ${{ else }}:
          - job:
            steps:
              - error: assert
  - ${{ else }}:
    - stage:
      jobs:
        - job:
          steps:
            - error: assert
