on:
  workflow_call:
    secrets:
      TEST:
        required: true
jobs:
  _:
    runs-on: self-hosted
    environment: test
    steps:
    - run: exit ${{ secrets.TEST == 'topsecret' && secrets.OPT == 'testsec' && '0' || '1' }}