# ExpectedException: TemplateValidationException
# ExpectedErrorMessage: pipeline-unexpected.yml (Line: 9, Col: 17): Unexpected parameter 'unexpected'
trigger: none

steps:
- template: steps.yml
  parameters:
    required: 'present'
    unexpected: 'bogus'