on:
  workflow_call:
    secrets:
      TEST:
        required: true
jobs:
  myjoba:
    runs-on: self-hosted
    steps:
    - run: |
        echo secrets.Test: ${{secrets.Test == 'Overriden'}}
        exit ${{secrets.Test == 'Overriden' && '0' || '1'}}