on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/github-script@v5
      with:
        github-token: none
        script: |
          if(!process.env['myfirstmultilinesecret'] || !process.env['MyLastMultilineSecret'] || (process.env['myfirstmultilinesecret'].match(/\n/g) || []).length != 2 || (process.env['MyLastMultilineSecret'].match(/\n/g) || []).length != 2 || process.env['myfirstmultilinesecret'] !== process.env['MyLastMultilineSecret']) {
            process.exit(1)
          }
      env:
        myfirstmultilinesecret: ${{env.myfirstmultilinesecret}}
        MyLastMultilineSecret: ${{env.MyLastMultilineSecret}}