on: push
name: test if skipped jobs are working
jobs:
  skipped:
    name: skipped-${{ github.event_name }}
    if: 'false'
    runs-on: self-hosted
    steps:
    - run: exit 1
  failAfterSkipped:
    needs: skipped
    runs-on: self-hosted
    steps:
    - run: exit 1
  failAfterSkipped2:
    if: success('skipped') || failure('skipped') || cancelled()
    needs: skipped
    runs-on: self-hosted
    steps:
    - run: exit 1
  failAfterSkipped3:
    if: success() || failure() || cancelled()
    needs: skipped
    runs-on: self-hosted
    steps:
    - run: exit 1