on:
  push:
        
permissions: {}
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        _:
        - prop1: val1
          prop2: val2
          prop3: val3
          sq:
          - a
          - b
          - c
        - prop1: val4
          prop2: val2
          prop3: val3
          sq:
          - a
          - b
          - c
        exclude:
        - _:
            prop1: val4
            sq:
            - a
        include:
        - _:
            prop1: val1
            sq:
            - a
          prop4: test
        - _:
            prop1: val1
            prop2: val2
            sq:
            - a
            - b
          prop5: test
        - _:
            prop1: val1
            prop3: val3
            sq:
            - a
            - b
            - c
          prop6: test
            
    steps:
    - run: |-
       github:
       ${{tojson(github)}}
       matrix:
       ${{tojson(matrix)}}
       strategy:
       ${{tojson(strategy)}}
       vars:
       ${{tojson(vars)}}
       secrets:
       ${{tojson(secrets)}}
       inputs:
       ${{tojson(inputs)}}
      shell: cat {0}
      if: runner.os != 'windows'
    - run: exit ${{ matrix._.prop1 == 'val1' && matrix._.prop2 == 'val2' && matrix._.prop3 == 'val3' && matrix._.sq[0] == 'a' && matrix._.sq[1] == 'b' && matrix._.sq[2] == 'c' && !matrix._.sq[3] && matrix.prop4 == 'test' && matrix.prop5 == 'test' && matrix.prop6 == 'test' && '0' || '1' }}
    