# ExpectedException: TemplateValidationException
# ExpectedMessage: A mapping was not expected

variables:
- name: Hello World
  value: ${{ converttojson(parameters.y) }}
- template: vars3.yml
  parameters:
    y:
      stage: meh
      variables:
      - template: vars2.yml
        parameters:
          y:
            stage: meh
            condition: fake
steps:
- bash: echo Test