# Based on https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-container?view=azure-pipelines#examples-1
resources:
  containers:
  - container: u20
    image: ubuntu:20.04

  - container: u22
    image: ubuntu:22.04

  - container: u24
    image: ubuntu:24.04

jobs:
- job: RunInContainer

  strategy:
    matrix:
      ubuntu20:
        containerResource: u20
      ubuntu22:
        containerResource: u22
      ubuntu24:
        containerResource: u24

  container: $[ variables['containerResource'] ]

  steps:
  - script: printenv
