trigger: none

stages:
- stage: build
  jobs:
  - job:
    steps:
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        feedsToUse: config
        nugetConfigPath: nuget.config
