# ExpectedException: TemplateValidationException
# ExpectedErrorMessage: true | y | yes | on | false | n | no | off was expected
jobs:
- ${{ each x in split('yes,no,n,y,true,false,TRUE,False,On,Off,#', ',') }}:
  - job:
    steps:
    - script: echo test
      continueOnError: ${{ x }}
