runs:
  using: docker
  image: docker://mcr.microsoft.com/windows/nanoserver:20H2
  entrypoint: cmd
  args: 
  - /c
  - |-
      echo GITHUB_WORKSPACE: %GITHUB_WORKSPACE% && echo ::add-matcher::%GITHUB_WORKSPACE%\problem.json && echo ::add-matcher::problem.json