name: Runner CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - gha_test
    - releases/*
    paths-ignore:
    - '**.md'    
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '**.md'    

jobs:
  build:
    strategy:
      matrix:
        runtime: [ linux-x64, linux-arm64, linux-arm, win-x64, osx-x64 ]
        include:
        - runtime: linux-x64
          os: ubuntu-latest
          devScript: ./dev.sh
          scriptSuffix: .sh
          elevate: "sudo "

        - runtime: linux-arm64
          os: ubuntu-latest
          devScript: ./dev.sh
          scriptSuffix: .sh
          elevate: "sudo "

        - runtime: linux-arm
          os: ubuntu-latest
          devScript: ./dev.sh
          scriptSuffix: .sh
          elevate: "sudo "

        - runtime: osx-x64
          os: macOS-latest
          devScript: ./dev.sh
          scriptSuffix: .sh
          elevate: "sudo "

        - runtime: win-x64
          os: windows-latest
          devScript: ./dev
          exeSuffix: .exe
          scriptSuffix: .cmd

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    # Build runner layout
    - name: Build & Layout Release
      run: |
        ${{ matrix.devScript }} layout Release ${{ matrix.runtime }}
      working-directory: src

    # Run tests
    - name: L0
      run: |
        ${{ matrix.devScript }} test
      working-directory: src
      if: matrix.runtime != 'linux-arm64' && matrix.runtime != 'linux-arm'

    # Create runner package tar.gz/zip
    - name: Package Release
      if: github.event_name != 'pull_request'
      run: |
        ${{ matrix.devScript }} package Release
      working-directory: src

    # Upload runner package tar.gz/zip as artifact
    - name: Publish Artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v1
      with:
        name: runner-package-${{ matrix.runtime }}
        path: _package
    - name: Setup
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $obj = Get-Content "_layout/bin/appsettings.json" | ConvertFrom-Json
        $obj.'Runner.Server'.GITHUB_TOKEN = $Env:GITHUB_TOKEN
        $obj | ConvertTo-Json -Depth 20 | Set-Content  "_layout/bin/appsettings.json"
    - name: Test
      shell: bash
      if: matrix.runtime != 'linux-arm64' && matrix.runtime != 'linux-arm'
      run: |
        pushd _layout/bin
        ./Runner.Server${{ matrix.exeSuffix }} &
        serverpid=$!
        sleep 20
        # Test run job without a runner
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../src/Runner.Client/workflow.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000 && exit 1 || [[ "$?" = "1" ]]
        pushd ..
        ./config${{ matrix.scriptSuffix }} --unattended --url http://localhost:5000/runner/server --token "ThisIsIgnored"
        ./run${{ matrix.scriptSuffix }} &
        workerpid=$!
        sleep 20
        popd
        # Test run job with runner
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../src/Runner.Client/workflow.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../testworkflows/globalenv.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../testworkflows/localenv.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../testworkflows/stepenv.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../testworkflows/matrixtest.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../testworkflows/skipped.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000
        ./Runner.Client${{ matrix.exeSuffix }} --workflow ../../testworkflows/eventwithnulltoken.yml --payload ../../src/Runner.Client/payload.json --server http://localhost:5000
        #Test using parallel 1
        ./Runner.Client${{ matrix.exeSuffix }} -P ubuntu-latest=-self-hosted -W ../../testworkflows/matrixtest.yml --parallel 1
        #Test using parallel 0, this have to fail
        ./Runner.Client${{ matrix.exeSuffix }} -P ubuntu-latest=-self-hosted -W ../../testworkflows/matrixtest.yml --parallel 0 && exit 1 || [[ "$?" = "1" ]]
        ./Runner.Client${{ matrix.exeSuffix }} -W ../../testworkflows/artifact.yml

        kill $workerpid
        kill $serverpid
        popd
    - name: Test cache
      if: matrix.runtime != 'linux-arm64' && matrix.runtime != 'linux-arm'
      shell: bash
      run: |
        pushd _layout/bin
        ./Runner.Client${{ matrix.exeSuffix }} -P ubuntu-latest=-self-hosted -W ../../testworkflows/cache.yml
        popd
