on:
  push:
    branches:
    - main
  pull_request:
jobs:
  deploy:
    # Allow one concurrent deployment
    concurrency:
      group: ${{ github.event_name == 'push' && 'pages' || github.run_id }}
      cancel-in-progress: true
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: ${{ github.event_name == 'push' && 'github-pages' || '' }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://${{ github.repository_owner }}.github.io${{ github.repository_owner != github.event.repository.name && format('/{0}', github.event.repository.name) || '' }}
      REPO_NAME: ${{ github.repository_owner != github.event.repository.name && format('{0}-{1}', github.repository_owner, github.event.repository.name) || github.repository_owner }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build ExpandAzurePipelines
        run: dotnet publish src/ExpandAzurePipelines -c Release --output out
      - name: Make layout
        run: |
          mkdir webapp
          mv out/wwwroot webapp/ExpandAzurePipelines
      - name: Setup Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'webapp'
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v1