on: push
jobs:
  matrixtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test1: [a]
        test2: [a,b,c]
        include:
        - test1: a
          test3: sh
        - test1: a
          test3: bash
        - test1: a
          test4: bash
        - test2: d
          test4: sh
        - test1: b
          test4: fish
        - test1: b
          test4: fish
          test3: as
    steps:
    - run: echo '${{matrix.test1}}-${{matrix.test2}}-${{matrix.test3}}-${{matrix.test4}}'
