on: workflow_dispatch
name: update-wwwroot
jobs:
  update-wwwroot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
    - run: |
        npm install
        npm run build
      working-directory: src/Runner.Server/webpage
    - run: |
        npm install
      working-directory: src/Runner.Server/localcheckout
    - run: |
        tar czf wwwroot/localcheckout.tar.gz localcheckout/
        zip -r wwwroot/localcheckout.zip localcheckout/
      working-directory: src/Runner.Server
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update localcheckout"
        git push
      continue-on-error: true